---
    deployment:
        tasks:
            - export DEPLOYPATH=/home/bgitbrentyns/public_html/
            - /bin/cp -R public/_nuxt $DEPLOYPATH
            - /bin/cp -R public/about $DEPLOYPATH
            - /bin/cp -R public/contact $DEPLOYPATH
            - /bin/cp -R public/map $DEPLOYPATH
            - /bin/cp -R public/unmined $DEPLOYPATH
            - /bin/cp public/_payload.json
            - /bin/cp public/200.html $DEPLOYPATH
            - /bin/cp public/404.html $DEPLOYPATH
            - /bin/cp public/favicon.ico $DEPLOYPATH
            - /bin/cp public/index.html $DEPLOYPATH
            - /bin/cp public/license.txt $DEPLOYPATH
            - /bin/cp public/README.md $DEPLOYPATH
            - /bin/cp public/robots.txt $DEPLOYPATH
            - /bin/cp public/sitemap.txt $DEPLOYPATH